# Generated by Django 3.2.6 on 2021-08-25 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Event name')),
                ('content', models.TextField(verbose_name='Description')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Published')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.period')),
            ],
            options={
                'ordering': ['published'],
            },
        ),
    ]
